#pragma once

using namespace ATL;

template <class T>
class CProxy_IWebVoipCtrlEvents : public IConnectionPointImpl<T, &__uuidof(_IWebVoipCtrlEvents), CComDynamicUnkArray>
{
	// WARNING: This class may be regenerated by the wizard
public:
};
